baseURL: https://new.scholacantorum.org/
ignoreFiles:
    - README.md
languageCode: en-us
staticDir:
    - static
    - static-sandbox
title: Schola Cantorum
params:
    env: development
    stripeKey: pk_test_QPwvhWbGaakWn7DGcco8J5Nd
