baseURL: https://new.scholacantorum.org/
ignoreFiles:
    - README.md
    - asset-archive/.*
languageCode: en-us
params:
    env: development
    stripeMode: test
    stripeKey: pk_test_QPwvhWbGaakWn7DGcco8J5Nd
staticDir:
    - static
    - static-sandbox
title: Schola Cantorum
