baseURL: https://new.scholacantorum.org/
ignoreFiles:
  - README.md
  - asset-archive/.*
languageCode: en-us
menu:
  dropdown:
    - name: Members Web Site
      title: Members Web Site
      url: https://members.scholacantorum.org/
      weight: 80
params:
  env: development
  stripeKey: pk_test_QPwvhWbGaakWn7DGcco8J5Nd
  ordersURL: http://localhost:8200
  galaRegURL: http://localhost:9000/register
staticDir:
  - static
  - static-sandbox
title: Schola Cantorum
markup:
  goldmark:
    renderer:
      unsafe: true
